export const START_DATE = 'START_DATE'
export const END_DATE = 'END_DATE'
export const PICKUP = 'PICKUP'
export const DROPOFF = 'DROPOFF'
export const RENTAL_COMPANY = 'RENTAL_COMPANY'
export const SPACESHIP_TYPE = 'SPACESHIP_TYPE'
export const PRICE_RANGE = 'PRICE_RANGE'
export const CAPACITY = 'CAPACITY'
